import { UI_IMAGES } from "../storage/hud/game-menu.storage.js";
import { LIFEBAR, COINBAR, POISONBAR } from "../storage/hud/hud.storage.js";
import { SHARKY_WAITING, SHARKY_LONG_WAITING, SHARKY_SWIMMING, SHARKY_FIN_SLAP, SHARKY_BUBBLE_ATTACK, SHARKY_POISON_BUBBLE_ATTACK, SHARKY_ELECTRIC_SHOCK, SHARKY_HURT_POISONED, SHARKY_DEAD_POISONED } from "../storage/characters/sharky.storage.js";
import { GREEN_PUFFERFISH_SWIMMING, RED_PUFFERFISH_SWIMMING, RAINBOW_PUFFERFISH_SWIMMING, GREEN_PUFFERFISH_TRANSITION, RED_PUFFERFISH_TRANSITION, RAINBOW_PUFFERFISH_TRANSITION, GREEN_PUFFERFISH_BUBBLE_SWIMMING, RED_PUFFERFISH_BUBBLE_SWIMMING, RAINBOW_PUFFERFISH_BUBBLE_SWIMMING, GREEN_PUFFERFISH_DEAD, RED_PUFFERFISH_DEAD, RAINBOW_PUFFERFISH_DEAD } from "../storage/characters/enemies/pufferfish.storage.js";
import { LILA_JELLYFISH_SWIMMING, YELLOW_JELLYFISH_SWIMMING, LILA_JELLYFISH_DEAD, LILA_JELLYFISH_SUPER_DEAD, YELLOW_JELLYFISH_DEAD, YELLOW_JELLYFISH_SUPER_DEAD, LILA_JELLYFISH_SUPER_DANGEROUS, YELLOW_JELLYFISH_SUPER_DANGEROUS } from "../storage/characters/enemies/jellyfish.storage.js";
import { BOSS_FLOATING, BOSS_HURT, BOSS_DEAD, BOSS_INTRO, BOSS_ATTACK } from "../storage/characters/enemies/boss.storage.js";
import { COIN, POISON } from "../storage/entities/collectibles.storage.js";
import { BUBBLE_IMAGES, POISON_BUBBLE_IMAGES } from "./entities/bubble.configs.js";
import { BACKGROUND } from "./background/background.configs.js";
import { ENTITIES } from "./entities/entity.configs.js";
import { COINS, POISONS } from "./entities/collectibles.configs.js";
import { ENEMIES } from "./characters/enemy.configs.js";
import { SHARKY } from "./characters/sharky.configs.js";
import { HUD } from "./hud/hud.configs.js";

export const IMAGE_PRELOAD_SOURCES = [
    Object.values(UI_IMAGES),

    LIFEBAR,
    COINBAR,
    POISONBAR,

    SHARKY_WAITING,
    SHARKY_LONG_WAITING,
    SHARKY_SWIMMING,
    SHARKY_FIN_SLAP,
    SHARKY_BUBBLE_ATTACK,
    SHARKY_POISON_BUBBLE_ATTACK,
    SHARKY_ELECTRIC_SHOCK,
    SHARKY_HURT_POISONED,
    SHARKY_DEAD_POISONED,

    GREEN_PUFFERFISH_SWIMMING,
    RED_PUFFERFISH_SWIMMING,
    RAINBOW_PUFFERFISH_SWIMMING,
    GREEN_PUFFERFISH_TRANSITION,
    RED_PUFFERFISH_TRANSITION,
    RAINBOW_PUFFERFISH_TRANSITION,
    GREEN_PUFFERFISH_BUBBLE_SWIMMING,
    RED_PUFFERFISH_BUBBLE_SWIMMING,
    RAINBOW_PUFFERFISH_BUBBLE_SWIMMING,
    GREEN_PUFFERFISH_DEAD,
    RED_PUFFERFISH_DEAD,
    RAINBOW_PUFFERFISH_DEAD,

    LILA_JELLYFISH_SWIMMING,
    YELLOW_JELLYFISH_SWIMMING,
    LILA_JELLYFISH_DEAD,
    LILA_JELLYFISH_SUPER_DEAD,
    YELLOW_JELLYFISH_DEAD,
    YELLOW_JELLYFISH_SUPER_DEAD,
    LILA_JELLYFISH_SUPER_DANGEROUS,
    YELLOW_JELLYFISH_SUPER_DANGEROUS,

    BOSS_FLOATING,
    BOSS_HURT,
    BOSS_DEAD,
    BOSS_INTRO,
    BOSS_ATTACK,

    COIN,
    POISON,

    BUBBLE_IMAGES,
    POISON_BUBBLE_IMAGES,

    BACKGROUND,
    ENTITIES,
    COINS,
    POISONS,
    ENEMIES,
    SHARKY,
    Object.values(HUD)
];